#! /usr/bin/expect

set timeout -1
spawn python3 main.py
expect "MON> "
send "l 20 mult.asm\n"
expect "MON> "
send "d 10\n"
expect "]> "
send "5\n"
expect "]> "
send "3\n"
expect "]> "
send ".\n"
expect "MON> "
send "l 100 fib.asm\n"
expect "MON> "
send "d 50\n"
expect "]> "
send "7\n"
expect "]> "
send ".\n"
expect "MON> "
send "r\n"
expect "MON> "
send "s 10 15\n"
expect "MON> "
send "s 500 510\n"
expect "MON> "
send "\n"